#ifndef FONTS_UBUNTU_H
#define FONTS_UBUNTU_H

#include "stm32f10x.h"
/*****************************************************************************
 * File: Fonts_Ubuntu_18_26_36.h generated by FontGen 1.0

*  This program is free software; you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation; either version 2 of the License, or
*  (at your option) any later version.

*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.

*  You should have received a copy of the GNU General Public License
*  along with this program; if not, write to the Free Software
*  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA */


#define	F_START 						32
#define	F_END							126
#define	F_HEIGHT_UBUNTU18				21
#define	F_HEIGHT_UBUNTU26				31
#define	F_HEIGHT_UBUNTU36				42


#define F_WIDTH_POS(CHAR)				(CHAR - F_START)
#define F_SIZE(CHAR, HEIGHT)			(F_WIDTH_POS(CHAR) * HEIGHT)

typedef struct
{
	uint16_t * f_offset_table;
	uint8_t * f_width_table;
	uint8_t * f_data_table;
	uint8_t f_height;
}font_t;


extern font_t font_ubuntu18;
extern font_t font_ubuntu26;
extern font_t font_ubuntu36;



#endif
